package com.customerapplicationservice.repositories

import com.customerapplicationservice.modal.CustomerLoanApplication
import org.springframework.data.mongodb.repository.ReactiveMongoRepository

interface CustomerLoanApplicationRepo: ReactiveMongoRepository<CustomerLoanApplication,String> {
}